### ISSUE TITLE
Curly Braces on the same line or on a new line?

### ISSUE THREAD

**Issue by Unthrottled** [mskelton/ama#2]
```javascript
const theCorrectWay = () => {
 console.log('The only way');
}

const theWrongWay = () => 
{
 console.log('Why must it be like this');
}
```

This is one of the few formatting things I care about, do you have any other strong style preferences?

**Comment by mskelton** [comment]
Unless it's a language like C#, I always would do the first with the bracket on the same line.

**Comment by Unthrottled** [comment]
> Unless it's a language like C#, 

So do you conform to various language best practices, or do you stick to a convention and drag it all over the place (like CamelCase in Python)? Because when I programed in C#, the first thing I did was to put the curly braces back where they belong 😄

**Comment by mskelton** [comment]
I usually stick to language conventions.  Underscores in Python, camel case in JS/Go, etc.
